version: '3' 
services:
  docker-project-template:
    image: openkbs/docker-project-template
    build:
      context: ./Dockerfile
    container_name: docker-project-template
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./docker.env
    volumes:
      - ./workspace:/home/developer/workspace

